
#################################################
# Read configuration
#################################################
#read_eb_conf ../evtbuild/eb.conf
#read_addrange_db ../main/address_range.db

#################################################
#Load TRB database files
#################################################
!ifndef NOCTS
  read_trb_db ../cts/trb.db
!endif

#!ifndef NOCERBEROS
# read_trb_db ../cerberos/trb.db
#!endif

!ifndef NOSTART
  read_trb_db ../start/trb.db
!endif

!ifndef NOHUB
  read_trb_db ../hub/trb.db
!endif

#################################################
#Load FPGA designs
#################################################
!ifndef CONFIGONLY
  # Program CTS,SCS,CERBEROS FPGA 
  exec_cmd{local} echo "Programming TRB-FPGA"
#  exec_cmd{pexor}   jam_trbv2 --trb -aRUN_XILINX_PROC  /home/hadaq/mdc_oepb/stapl/trb2_control_20101110.stapl
# exec_cmd{cer}   jam_trbv2 --trb -aRUN_XILINX_PROC  /home/hadaq/tof/fpga/20101110_tof_a.stapl
#  exec_cmd{cer}   jam_trbv2 --trb -aRUN_XILINX_PROC  /home/hadaq/20101111_rpc_e.stapl
  exec_cmd{start} jam_trbv2 --trb -aRUN_XILINX_PROC  /home/hadaq/tof/fpga/20101110_tof_a.stapl
#  exec_cmd{start} jam_trbv2 --trb -aRUN_XILINX_PROC  /home/hadaq/20101111_rpc_e.stapl
  wait

  # Program 1st AddOn FPGA
  exec_cmd{local} echo "Programming FPGA1"
  #exec_cmd{hub}    jam_trbv2 --addononly -aFP /home/hadaq/hub/hub2_fpga1_single_20100802.stp
  exec_cmd{hub}  jam_trbv2 --addon -aFP /home/hadaq/hub/hub2_fpga1_full_20110517.stp
  exec_cmd{cts}     jam_trbv2 --addon -aFP /home/hadaq/cts/20110411_cts_fpga1_c.stp
#  exec_cmd{cts}     jam_trbv2 --addon -aFP /home/hadaq/cts/20110901_cts_fpga1_a.stpy
#  exec_cmd{cts}     jam_trbv2 --addononly -aFP /home/hadaq/cts/20120410_cts_fpga1_only_etrax_a.stp
  wait

  # Program 2nd AddOn FPGA
  exec_cmd{local} echo "Programming FPGA2"
  exec_cmd{hub} jam_trbv2 --addon -aFP /home/hadaq/hub/hub2_fpga2_full_20110523.stp
  exec_cmd{cts}     jam_trbv2 --addon -aFP /home/hadaq/cts/20110411_cts_fpga2_e.stp
#  exec_cmd{cts}     jam_trbv2 --addon -aFP /home/hadaq/cts/20110901_cts_fpga2_a.stp
#  exec_cmd{cts}     jam_trbv2 --addononly -aFP /home/hadaq/cts/20120321_cts_fpga2_only_etrax_a.stp

#  # Wait for links
  exec_cmd{local} echo "---------Waiting 8 seconds for FPGAs to boot   ----------------"  
  exec_cmd{local} sleep 8
  exec_cmd{local} echo "---------Programming finished. Starting Configuration----------"
  wait

!endif

!ifndef NORESET
  exec_cmd{local} echo "network reset"
  #exec_cmd{local} trbcmd reset
  exec_cmd{pexor} trbcmd reset
  wait
  exec_cmd{local} sleep 1
  wait
!endif

#################################################
#Configuration via TrbNet
#################################################

#Hub boards
  !ifndef NOHUB
    exec_cmd{local} echo "Configure Hubs"
    exec_script{pexor} ../hub/startup.script
    wait
  !endif

#Configuration on TRBs
  exec_cmd{local} echo "Configuring TDC on TRBs"
  !ifndef NOCERBEROS
   exec_script{cer} ../cerberos/configure_cerberos.script
  !endif
  !ifndef NOSTART
    exec_script{start} ../start/configure_start.script
  !endif
  !ifndef NOCTS
    exec_script{cts} ../cts/configure_cts.script
  !endif

#Central boards / CTS / SCS
  !ifndef NOCTS
    exec_cmd{local} echo "Configure CTS"
    exec_script{pexor} ../cts/startup.script
  !endif

#CERBEROS
  !ifndef NOCERBEROS
   exec_cmd{local} echo "Configure CERBEROS"
   exec_script{pexor} ../cerberos/startup.script
  !endif

#START
  !ifndef NOSTART
    exec_cmd{local} echo "Configure START"
    exec_script{pexor} ../start/startup.script
  !endif
 
wait
exec_cmd{local} echo "---------Configuration finished. You may start DAQ now.----------"

